version: '3'
services:
  react-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
