"""photo table's rows update

Revision ID: 00b65b610077
Revises: 4e5073a847f6
Create Date: 2024-03-17 12:54:12.831773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b65b610077'
down_revision: Union[str, None] = '4e5073a847f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('filename', sa.String(), nullable=False))
    op.drop_constraint('photo_file_path_key', 'photo', type_='unique')
    op.drop_constraint('photo_url_key', 'photo', type_='unique')
    op.create_unique_constraint(None, 'photo', ['filename'])
    op.drop_column('photo', 'url')
    op.drop_column('photo', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('photo', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'photo', type_='unique')
    op.create_unique_constraint('photo_url_key', 'photo', ['url'])
    op.create_unique_constraint('photo_file_path_key', 'photo', ['file_path'])
    op.drop_column('photo', 'filename')
    # ### end Alembic commands ###
