"""driver table added and company, weighing tables changes

Revision ID: 05caa3c4e495
Revises: 344babbc5456
Create Date: 2024-03-26 13:54:24.840686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05caa3c4e495'
down_revision: Union[str, None] = '344babbc5456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('company', sa.Column('bin', sa.String(), nullable=True))
    op.add_column('company', sa.Column('is_debtor', sa.Boolean(), nullable=False, server_default="False"))
    op.add_column('company', sa.Column('debtor_note', sa.String(), nullable=True))
    op.add_column('transport', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transport', 'driver', ['driver_id'], ['id'])
    op.drop_column('transport', 'driver_fullname')
    op.add_column('weighing', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'weighing', 'driver', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weighing', type_='foreignkey')
    op.drop_column('weighing', 'driver_id')
    op.add_column('transport', sa.Column('driver_fullname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transport', type_='foreignkey')
    op.drop_column('transport', 'driver_id')
    op.drop_column('company', 'debtor_note')
    op.drop_column('company', 'is_debtor')
    op.drop_column('company', 'bin')
    op.drop_table('driver')
    # ### end Alembic commands ###
