"""company type enum update

Revision ID: 113dd2c867cf
Revises: 5607ad7cc2df
Create Date: 2024-04-13 20:42:16.962927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '113dd2c867cf'
down_revision: Union[str, None] = '5607ad7cc2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'companytypeenum', ['TOO', 'IP', 'PP', 'AO', 'Filial'],
                        [TableReference('company', 'company_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'companytypeenum', ['TOO', 'IP', 'PP'],
                        [TableReference('company', 'company_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
