"""make_detail_id_nullable_in_weighing

Revision ID: 1641756e885e
Revises: a972aa4de032
Create Date: 2025-06-26 08:24:39.521505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1641756e885e'
down_revision: Union[str, None] = 'a972aa4de032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weighing', 'detail_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weighing', 'detail_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
