"""table names changed

Revision ID: 1651710416b8
Revises: 53c0ca449a88
Create Date: 2024-03-04 17:33:59.476049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '1651710416b8'
down_revision: Union[str, None] = '53c0ca449a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_id', table_name='user')
    op.drop_index('ix_User_login', table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.sync_enum_values('public', 'companyfuncenum', ['supplier', 'customer', 'all', 'our'],
                        [TableReference('company', 'company_func')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'companyfuncenum', ['supplier', 'customer', 'all'],
                        [TableReference('company', 'company_func')],
                        enum_values_to_rename=[])
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index('ix_User_login', 'user', ['login'], unique=True)
    op.create_index('ix_User_id', 'user', ['id'], unique=False)
    # ### end Alembic commands ###
