"""add status field to weighing

Revision ID: 22168e56e192
Revises: 1641756e885e
Create Date: 2025-06-27 08:34:32.148840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22168e56e192'
down_revision: Union[str, None] = '1641756e885e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weighing', sa.Column('status', sa.String(), nullable=False, server_default='waiting_first'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weighing', 'status')
    # ### end Alembic commands ###
