"""the order of notification statuses has been changed

Revision ID: 29ac4c679648
Revises: 113dd2c867cf
Create Date: 2024-04-15 17:29:29.513357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '29ac4c679648'
down_revision: Union[str, None] = '113dd2c867cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'notificationstatusenum', ['initial', 'read', 'not_read'],
                        [TableReference('request', 'is_call', existing_server_default="'initial'::notificationstatusenum"), TableReference('request', 'is_abs', existing_server_default="'initial'::notificationstatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'notificationstatusenum', ['initial', 'not_read', 'read'],
                        [TableReference('request', 'is_call', existing_server_default="'initial'::notificationstatusenum"), TableReference('request', 'is_abs', existing_server_default="'initial'::notificationstatusenum")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
