"""weighing: is_return, deactivate_note, return_note rows added

Revision ID: 29b858830d81
Revises: 7cc16677c2bb
Create Date: 2024-03-19 12:21:51.250817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b858830d81'
down_revision: Union[str, None] = '7cc16677c2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weighing', sa.Column('is_return', sa.Boolean(), nullable=False, server_default="False"))
    op.add_column('weighing', sa.Column('deactivate_note', sa.String(), nullable=True))
    op.add_column('weighing', sa.Column('return_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weighing', 'return_note')
    op.drop_column('weighing', 'deactivate_note')
    op.drop_column('weighing', 'is_return')
    # ### end Alembic commands ###
