"""initial purpose cubature added for request

Revision ID: 344babbc5456
Revises: b64df4de2f3d
Create Date: 2024-03-25 14:03:45.877235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344babbc5456'
down_revision: Union[str, None] = 'b64df4de2f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('initial_purpose_cubature', sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'initial_purpose_cubature')
    # ### end Alembic commands ###
