"""request: descrption row added

Revision ID: 470e56e14018
Revises: 8c16af4cf747
Create Date: 2024-05-01 22:42:33.138324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470e56e14018'
down_revision: Union[str, None] = '8c16af4cf747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'description')
    # ### end Alembic commands ###
