"""add company_id to user (barakat)

Revision ID: 4d01ba6d820e
Revises: 5b36d27bc76c
Create Date: 2025-06-26 06:44:47.503632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d01ba6d820e'
down_revision: Union[str, None] = '5b36d27bc76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inert_material_request', 'transport_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inert_material_request', 'carrier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inert_material_request', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inert_material_request', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inert_material_request', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'company_id')
    op.alter_column('inert_material_request', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('inert_material_request', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inert_material_request', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inert_material_request', 'carrier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inert_material_request', 'transport_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
