"""new table: photo added

Revision ID: 4e5073a847f6
Revises: 892abca12029
Create Date: 2024-03-16 17:57:43.735094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5073a847f6'
down_revision: Union[str, None] = '892abca12029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('is_attached', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('url')
    )
    op.add_column('weighing', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'weighing', 'photo', ['photo_id'], ['id'])
    op.drop_column('weighing', 'photo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weighing', sa.Column('photo_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weighing', type_='foreignkey')
    op.drop_column('weighing', 'photo_id')
    op.drop_table('photo')
    # ### end Alembic commands ###
