"""request: by_call row added

Revision ID: 5581fbf72085
Revises: ac115387e561
Create Date: 2024-04-17 15:29:45.670652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5581fbf72085'
down_revision: Union[str, None] = 'ac115387e561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('by_call', sa.Boolean(), nullable=False, server_default="False"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'by_call')
    # ### end Alembic commands ###
