"""cmp: ip_address added

Revision ID: 5607ad7cc2df
Revises: 05caa3c4e495
Create Date: 2024-03-28 17:13:26.635047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5607ad7cc2df'
down_revision: Union[str, None] = '05caa3c4e495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concrete_mixing_plant', sa.Column('ip_address', sa.String(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concrete_mixing_plant', 'ip_address')
    # ### end Alembic commands ###
