"""request: new row auto_send_telegram added

Revision ID: 69c9f3fcc635
Revises: 470e56e14018
Create Date: 2024-06-03 18:18:50.006353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c9f3fcc635'
down_revision: Union[str, None] = '470e56e14018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('auto_send_telegram', sa.Boolean(), nullable=False, server_default="False"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'auto_send_telegram')
    # ### end Alembic commands ###
