"""weighing: old_tare_weight, old_brutto_weight rows added

Revision ID: 7cc16677c2bb
Revises: 00b65b610077
Create Date: 2024-03-18 19:27:00.624552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc16677c2bb'
down_revision: Union[str, None] = '00b65b610077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weighing', sa.Column('old_tare_weight', sa.Integer(), nullable=True))
    op.add_column('weighing', sa.Column('old_brutto_weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weighing', 'old_brutto_weight')
    op.drop_column('weighing', 'old_tare_weight')
    # ### end Alembic commands ###
