"""request: is_abs, is_call added

Revision ID: 892abca12029
Revises: 1651710416b8
Create Date: 2024-03-12 18:37:09.843147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from schemas.request import NotificationStatusEnum

# revision identifiers, used by Alembic.
revision: str = '892abca12029'
down_revision: Union[str, None] = '1651710416b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('initial', 'not_read', 'read', name='notificationstatusenum').create(op.get_bind())
    op.add_column('request', sa.Column('is_abs', postgresql.ENUM('initial', 'not_read', 'read', name='notificationstatusenum', create_type=False), nullable=False, server_default="initial"))
    op.add_column('request', sa.Column('is_call', postgresql.ENUM('initial', 'not_read', 'read', name='notificationstatusenum', create_type=False), nullable=False, server_default="initial"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'is_call')
    op.drop_column('request', 'is_abs')
    sa.Enum('initial', 'not_read', 'read', name='notificationstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
