"""permission: name unique constraint added

Revision ID: 8c16af4cf747
Revises: 5581fbf72085
Create Date: 2024-04-18 15:43:45.497416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c16af4cf747'
down_revision: Union[str, None] = '5581fbf72085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permission', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='unique')
    # ### end Alembic commands ###
