"""second_migration

Revision ID: 9d74a9928f22
Revises: 71a8f6ed7eac
Create Date: 2024-02-07 16:49:58.530882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d74a9928f22'
down_revision: Union[str, None] = '71a8f6ed7eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MaterialType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('MaterialTypeObject',
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_type_id'], ['MaterialType.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['Object.id'], ),
    sa.PrimaryKeyConstraint('material_type_id', 'object_id')
    )
    op.drop_table('MaterialObject')
    op.add_column('Material', sa.Column('material_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Material', 'MaterialType', ['material_type_id'], ['id'])
    op.drop_column('Material', 'material_type')
    op.alter_column('User', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Weighing', 'photo_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    sa.Enum('concrete', 'mortar', 'claydite_concrete', 'sand_concrete', 'high_quality_concrete', 'reinforced_concrete', 'other', name='materialtypeenum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('concrete', 'mortar', 'claydite_concrete', 'sand_concrete', 'high_quality_concrete', 'reinforced_concrete', 'other', name='materialtypeenum').create(op.get_bind())
    op.alter_column('Weighing', 'photo_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('Material', sa.Column('material_type', postgresql.ENUM('concrete', 'mortar', 'claydite_concrete', 'sand_concrete', 'high_quality_concrete', 'reinforced_concrete', 'other', name='materialtypeenum', create_type=False), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Material', type_='foreignkey')
    op.drop_column('Material', 'material_type_id')
    op.create_table('MaterialObject',
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['Material.id'], name='MaterialObject_material_id_fkey'),
    sa.ForeignKeyConstraint(['object_id'], ['Object.id'], name='MaterialObject_object_id_fkey'),
    sa.PrimaryKeyConstraint('material_id', 'object_id', name='MaterialObject_pkey')
    )
    op.drop_table('MaterialTypeObject')
    op.drop_table('MaterialType')
    # ### end Alembic commands ###
