"""request:is_finished added

Revision ID: a1aaee3ca0f1
Revises: e06d39cc994a
Create Date: 2024-02-24 22:11:42.512984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1aaee3ca0f1'
down_revision: Union[str, None] = 'e06d39cc994a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('is_finished', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Request', 'is_finished')
    # ### end Alembic commands ###
