"""user table: fullname not nullable

Revision ID: a4cffd9fe08e
Revises: 9d74a9928f22
Create Date: 2024-02-20 16:57:31.951615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cffd9fe08e'
down_revision: Union[str, None] = '9d74a9928f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Transport', 'carrier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('User', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Transport', 'carrier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
