"""add_detail_id_to_inert_material_request

Revision ID: a972aa4de032
Revises: 4d01ba6d820e
Create Date: 2025-06-26 08:08:18.589069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a972aa4de032'
down_revision: Union[str, None] = '4d01ba6d820e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inert_material_request', sa.Column('detail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inert_material_request', 'detail', ['detail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inert_material_request', type_='foreignkey')
    op.drop_column('inert_material_request', 'detail_id')
    # ### end Alembic commands ###
