"""weighing: old_bag_details row added

Revision ID: ac115387e561
Revises: 29ac4c679648
Create Date: 2024-04-16 18:50:02.193364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac115387e561'
down_revision: Union[str, None] = '29ac4c679648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weighing', sa.Column('old_bag_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weighing', 'old_bag_details')
    # ### end Alembic commands ###
