"""construction and receive method types constrints added

Revision ID: b64df4de2f3d
Revises: 34823734f950
Create Date: 2024-03-21 17:44:10.588583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64df4de2f3d'
down_revision: Union[str, None] = '34823734f950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction', sa.Column('construction_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'construction', 'construction_type', ['construction_type_id'], ['id'])
    op.add_column('receive_method', sa.Column('receive_method_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'receive_method', 'receive_method_type', ['receive_method_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receive_method', type_='foreignkey')
    op.drop_column('receive_method', 'receive_method_type_id')
    op.drop_constraint(None, 'construction', type_='foreignkey')
    op.drop_column('construction', 'construction_type_id')
    # ### end Alembic commands ###
