"""construction and receive method types added

Revision ID: bf0e6d7eccb2
Revises: dc8555ca2b36
Create Date: 2024-03-21 17:31:16.055231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf0e6d7eccb2'
down_revision: Union[str, None] = 'dc8555ca2b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('construction', 'construction_type')
    sa.Enum('horizontal', 'vertical', name='constructiontypeenum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('horizontal', 'vertical', name='constructiontypeenum').create(op.get_bind())
    op.add_column('construction', sa.Column('construction_type', postgresql.ENUM('horizontal', 'vertical', name='constructiontypeenum', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
