"""weighing:bag details row added

Revision ID: df6d7405bfba
Revises: a1aaee3ca0f1
Create Date: 2024-02-26 20:09:49.989390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6d7405bfba'
down_revision: Union[str, None] = 'a1aaee3ca0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Weighing', sa.Column('bag_details', sa.String(length=32), nullable=True, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Weighing', 'bag_details')
    # ### end Alembic commands ###
