"""material types: is_for_dependent, is_for_independent boolean rows added

Revision ID: e06d39cc994a
Revises: a4cffd9fe08e
Create Date: 2024-02-20 19:18:11.036732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06d39cc994a'
down_revision: Union[str, None] = 'a4cffd9fe08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MaterialType', sa.Column('is_for_dependent', sa.Boolean(), nullable=False, server_default="False"))
    op.add_column('MaterialType', sa.Column('is_for_independent', sa.Boolean(), nullable=False, server_default="False"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MaterialType', 'is_for_independent')
    op.drop_column('MaterialType', 'is_for_dependent')
    # ### end Alembic commands ###
