name: Simple deployment with SSH on manual trigger

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Cloudflare ZeroTrust
        uses: oHTGo/setup-cloudflare-warp-action@v0.3.1
        with:
          organization: ${{ secrets.ZEROTRUST_ORGANIZATION }}
          auth-client-id: ${{ secrets.AUTH_CLIENT_ID }}
          auth-client-secret: ${{ secrets.AUTH_CLIENT_SECRET }}

      - name: SSH into server and run commands
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "started deployment"
            cd ~/deploy/frontend
            git pull
            docker compose up -d --build
            echo "fin"
